DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Topics CASCADE;
DROP TABLE IF EXISTS Threads CASCADE;
DROP TABLE IF EXISTS Messages CASCADE;

CREATE TABLE Users (
    id SERIAL PRIMARY KEY, 
    username TEXT UNIQUE, 
    password TEXT,
    admin BOOLEAN
);

CREATE TABLE Topics (
    id SERIAL PRIMARY KEY,
    title TEXT UNIQUE,
    secret BOOLEAN
);

CREATE TABLE Threads (
    id SERIAL PRIMARY KEY,
    title TEXT,
    topic_id INTEGER REFERENCES Topics ON DELETE CASCADE,
    user_id INTEGER REFERENCES Users,
    time TIMESTAMP
);

CREATE TABLE Messages (
    id SERIAL PRIMARY KEY,
    content TEXT,
    thread_id INTEGER REFERENCES Threads ON DELETE CASCADE,
    user_id INTEGER REFERENCES Users,
    time TIMESTAMP
);

CREATE TABLE SecretThreadUsers (
    id INTEGER PRIMARY KEY,
    topic_id INTEGER REFERENCES Topics ON DELETE CASCADE,
    user_id INTEGER REFERENCES Users
);
